skip_tags: true

version: 2.0.{build}

image: Ubuntu2204

init:
    - git config --global core.autocrlf input

install:
  - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
  - chmod +x dotnet-install.sh
  - sudo ./dotnet-install.sh --version 10.0.203 --install-dir /usr/share/dotnet
  - npm install -g azurite
  
build_script:
    - (exec azurite -l ~/.data &)
    - sleep 5
    - dotnet tool restore
    - dotnet nake pack

artifacts:
- path: Artifacts\Release\*.nupkg
